# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hmi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_hmi(object):
    def setupUi(self, hmi):
        hmi.setObjectName("hmi")
        hmi.resize(800, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(hmi.sizePolicy().hasHeightForWidth())
        hmi.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(hmi)
        self.label.setGeometry(QtCore.QRect(11, 11, 171, 16))
        self.label.setObjectName("label")
        self.Controller_IP_Addr_Edit = QtWidgets.QLineEdit(hmi)
        self.Controller_IP_Addr_Edit.setGeometry(QtCore.QRect(11, 34, 108, 25))
        self.Controller_IP_Addr_Edit.setObjectName("Controller_IP_Addr_Edit")
        self.Connect_Controller_Btn = QtWidgets.QPushButton(hmi)
        self.Connect_Controller_Btn.setGeometry(QtCore.QRect(11, 65, 80, 21))
        self.Connect_Controller_Btn.setObjectName("Connect_Controller_Btn")
        self.label_3 = QtWidgets.QLabel(hmi)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 131, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(hmi)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 81, 16))
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(hmi)
        self.textEdit.setGeometry(QtCore.QRect(10, 190, 201, 171))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(hmi)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 130, 201, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.Connect_Controller_Status_Edit = QtWidgets.QLineEdit(hmi)
        self.Connect_Controller_Status_Edit.setGeometry(QtCore.QRect(100, 66, 31, 21))
        self.Connect_Controller_Status_Edit.setObjectName("Connect_Controller_Status_Edit")
        self.Exit_Btn = QtWidgets.QPushButton(hmi)
        self.Exit_Btn.setGeometry(QtCore.QRect(710, 370, 80, 25))
        self.Exit_Btn.setObjectName("Exit_Btn")
        self.tabWidget = QtWidgets.QTabWidget(hmi)
        self.tabWidget.setGeometry(QtCore.QRect(220, 10, 571, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 54, 17))
        self.label_2.setObjectName("label_2")
        self.Update_Setpoint_Edit = QtWidgets.QLineEdit(self.tab)
        self.Update_Setpoint_Edit.setGeometry(QtCore.QRect(80, 20, 113, 25))
        self.Update_Setpoint_Edit.setObjectName("Update_Setpoint_Edit")
        self.Run_Control_Btn = QtWidgets.QPushButton(self.tab)
        self.Run_Control_Btn.setGeometry(QtCore.QRect(20, 70, 80, 25))
        self.Run_Control_Btn.setObjectName("Run_Control_Btn")
        self.Stop_Control_Btn = QtWidgets.QPushButton(self.tab)
        self.Stop_Control_Btn.setGeometry(QtCore.QRect(110, 70, 91, 25))
        self.Stop_Control_Btn.setObjectName("Stop_Control_Btn")
        self.Update_Control_Config_Btn = QtWidgets.QPushButton(self.tab)
        self.Update_Control_Config_Btn.setGeometry(QtCore.QRect(270, 260, 181, 25))
        self.Update_Control_Config_Btn.setObjectName("Update_Control_Config_Btn")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(230, 20, 321, 231))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(10, 13, 54, 17))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(10, 43, 54, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(10, 73, 54, 17))
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(50, 13, 113, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(50, 43, 113, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(50, 73, 113, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(190, 10, 91, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(190, 40, 54, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(190, 70, 54, 17))
        self.label_10.setObjectName("label_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(230, 40, 61, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_9.setGeometry(QtCore.QRect(230, 70, 61, 25))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(50, 166, 113, 25))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(10, 136, 54, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(10, 106, 54, 17))
        self.label_12.setObjectName("label_12")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(50, 136, 113, 25))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(10, 166, 54, 17))
        self.label_13.setObjectName("label_13")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_12.setGeometry(QtCore.QRect(50, 106, 113, 25))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.checkBox = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox.setGeometry(QtCore.QRect(210, 140, 82, 23))
        self.checkBox.setObjectName("checkBox")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.Controller_IP_Port_Edit = QtWidgets.QLineEdit(hmi)
        self.Controller_IP_Port_Edit.setGeometry(QtCore.QRect(130, 34, 41, 25))
        self.Controller_IP_Port_Edit.setObjectName("Controller_IP_Port_Edit")

        self.retranslateUi(hmi)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(hmi)

    def retranslateUi(self, hmi):
        _translate = QtCore.QCoreApplication.translate
        hmi.setWindowTitle(_translate("hmi", "HMI"))
        self.label.setText(_translate("hmi", "Controller IP Address & Port:"))
        self.Controller_IP_Addr_Edit.setText(_translate("hmi", "192.168.10.120"))
        self.Connect_Controller_Btn.setText(_translate("hmi", "Connect"))
        self.label_3.setText(_translate("hmi", "Current Controle Mode"))
        self.label_5.setText(_translate("hmi", "System Status"))
        self.textEdit.setHtml(_translate("hmi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Normal</p></body></html>"))
        self.lineEdit_2.setText(_translate("hmi", "INITIALIZE"))
        self.Connect_Controller_Status_Edit.setText(_translate("hmi", "No"))
        self.Exit_Btn.setText(_translate("hmi", "Exit"))
        self.label_2.setText(_translate("hmi", "Set Point"))
        self.Update_Setpoint_Edit.setText(_translate("hmi", "0.0"))
        self.Run_Control_Btn.setText(_translate("hmi", "Run Control"))
        self.Stop_Control_Btn.setText(_translate("hmi", "Stop Control"))
        self.Update_Control_Config_Btn.setText(_translate("hmi", "Update Control Configurations"))
        self.label_4.setText(_translate("hmi", "Kp"))
        self.label_6.setText(_translate("hmi", "Ki"))
        self.label_7.setText(_translate("hmi", "Kd"))
        self.lineEdit_5.setText(_translate("hmi", "1.0"))
        self.lineEdit_6.setText(_translate("hmi", "1.0"))
        self.lineEdit_7.setText(_translate("hmi", "1.0"))
        self.label_8.setText(_translate("hmi", "Output Range:"))
        self.label_9.setText(_translate("hmi", "High"))
        self.label_10.setText(_translate("hmi", "Low"))
        self.lineEdit_8.setText(_translate("hmi", "100"))
        self.lineEdit_9.setText(_translate("hmi", "0"))
        self.lineEdit_10.setText(_translate("hmi", "0.001"))
        self.label_11.setText(_translate("hmi", "beta"))
        self.label_12.setText(_translate("hmi", "alpha"))
        self.lineEdit_11.setText(_translate("hmi", "1.0"))
        self.label_13.setText(_translate("hmi", "dt"))
        self.lineEdit_12.setText(_translate("hmi", "1.0"))
        self.checkBox.setText(_translate("hmi", "Auto?"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("hmi", "PID Gains"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("hmi", "Control Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("hmi", "Process Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("hmi", "System Monitoring"))
        self.Controller_IP_Port_Edit.setText(_translate("hmi", "60000"))
